# Generated by Django 4.0.2 on 2022-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('Date', models.DateField()),
                ('Accession_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=400)),
                ('Title', models.CharField(max_length=500)),
                ('Volume', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(max_length=500)),
                ('Publisher', models.CharField(max_length=400)),
                ('Year_Of_Publication', models.IntegerField(blank=True, null=True)),
                ('Source', models.CharField(blank=True, max_length=400, null=True)),
                ('Pages', models.IntegerField(blank=True, null=True)),
                ('Book_Number', models.IntegerField()),
                ('Bill_Number', models.IntegerField(blank=True, null=True)),
                ('Bill_Date', models.DateField(blank=True, null=True)),
                ('Withdrawn_Date', models.DateField(blank=True, null=True)),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_No', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
